name: flutter_iconfont_svg_builder
description: A new Flutter package project.
version: 0.0.5
homepage: http://gitlab.tqxd.com/flutter/plugins/flutter_iconfont_svg_builder

publish_to: https://pub.youzi.dev/


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  cli_util: ^0.3.5
  http: ^0.13.4
  recase: ^4.0.0
  path: ^1.8.0
  xml: ^5.3.1