name: flutter_qrscan_plugin
description: A new Flutter project.
version: 0.2.1
homepage: http://gitlab.tqxd.com/flutter/plugins/flutter_qrscan_plugin

publish_to: https://pub.youzi.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.qrscan_plugin
        pluginClass: FlutterQrScanPlugin
      ios:
        pluginClass: FlutterQrScanPlugin
  assets:
    - assets/svgs/

