name: json_partner
description: JSON code generator helper
version: 2.1.0+1
homepage: http://gitlab.tqxd.com/flutter/plugins/json_partner

publish_to: https://pub.youzi.dev/

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  process_run: ^0.12.2
  cli_util: ^0.3.3

dev_dependencies:
  lints: ^1.0.0
