name: i18n_runner
description: 国际化语言包翻译自动代码生成工具
homepage: http://gitlab.tqxd.com/flutter/plugins/i18n_runner

publish_to: https://pub.youzi.dev/
version: 1.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  crypto: ^3.0.1
  cli_util: ^0.3.3
  path: ^1.8.0

i18n_runner:
  files:
    json: lib/i18n/i18n.json
    i18n_keys: lib/generated/i18n_keys.dart
    translations: lib/i18n/translations/
  locale:
    benchmark: zhCN
    supports:
      zhCN: zh_CN
      zhTW: zh_TW
      en: en_US
      ko: ko
      ja: ja
      fr: fr
      es: es
